# from AddressProperties import AddressProperties
# from AddressesProperties import AddressesProperties
# from AdversaryProperties import AdversaryProperties
# from AdversariesProperties import AdversariesProperties
# from AttributesProperties import AttributesProperties
# from DocumentProperties import DocumentProperties
# from DocumentsProperties import DocumentsProperties
# from DnsResolutionProperties import DnsResolutionProperties
# from EmailProperties import EmailProperties
# from EmailsProperties import EmailsProperties
# from EmailAddressProperties import EmailAddressProperties
# from EmailAddressesProperties import EmailAddressesProperties
# from FileOccurrenceProperties import FileOccurrenceProperties
# from FileOccurrencesProperties import FileOccurrencesProperties
# from FileProperties import FileProperties
# from FilesProperties import FilesProperties
# from GroupsProperties import GroupsProperties
# from HostProperties import HostProperties
# from HostsProperties import HostsProperties
# from IncidentProperties import IncidentProperties
# from IncidentsProperties import IncidentsProperties
# from IndicatorProperties import IndicatorProperties
# from IndicatorsProperties import IndicatorsProperties
# from OwnersProperties import OwnersProperties
# from SecurityLabelProperties import SecurityLabelProperties
# from SecurityLabelsProperties import SecurityLabelsProperties
# from SignatureProperties import SignatureProperties
# from SignaturesProperties import SignaturesProperties
# from TagProperties import TagProperties
# from TagsProperties import TagsProperties
# from ThreatProperties import ThreatProperties
# from ThreatsProperties import ThreatsProperties
# from UrlProperties import UrlProperties
# from UrlsProperties import UrlsProperties
# from VictimPhoneProperties import VictimPhoneProperties
# from VictimPhonesProperties import VictimPhonesProperties
# from VictimProperties import VictimProperties
# from VictimsProperties import VictimsProperties
# from VictimAssetsProperties import VictimAssetsProperties
# from VictimEmailAddressProperties import VictimEmailAddressProperties
# from VictimEmailAddressesProperties import VictimEmailAddressesProperties
# from VictimNetworkAccountProperties import VictimNetworkAccountProperties
# from VictimNetworkAccountsProperties import VictimNetworkAccountsProperties
# from VictimSocialNetworkProperties import VictimSocialNetworkProperties
# from VictimSocialNetworksProperties import VictimSocialNetworksProperties
# from VictimWebSiteProperties import VictimWebSiteProperties
# from VictimWebSitesProperties import VictimWebSitesProperties
